spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/blog?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: honors
    password: 12345678